version: '3.2'
services:
  api:
    build: api
    ports:
      - "4010:4010"
    depends_on:
      - postgres
    links:
      - postgres
#  web:
#    build: web
#    ports:
#      - "4000:4000"
#    depends_on:
#      - api
  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=devpass
    restart: always
    volumes:
      - ./db_bootstrap.sql:/docker-entrypoint-initdb.d/db_bootstrap.sql
    ports:
      - "5432:5432" # Just for development
